package com.bist.zeromq.config;

public enum CommandCode
{

    NEW_CLIENT_REGISTERED_TO_TRACKER,
    NEW_SERVER_REGISTERED_TO_TRACKER,
    REGISTER_NEW_PROCESS_TO_TRACKER,
    REGISTER_NEW_PROCESS_TO_PEER,


}
