#!/usr/bin/env bash

##Usage : ./clientProcess [peerCommandPort] [instanceId] [messageSize] [queryType]
##Usage : ./clientProcess  20123 1 0 0

VERSION=$(cat ../version.txt)


"${JAVA_HOME}"/bin/java \
    -cp ../target/zeromq-${VERSION}-jar-with-dependencies.jar \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+TrustFinalNonStaticFields \
    -XX:+UnlockDiagnosticVMOptions \
    -XX:GuaranteedSafepointInterval=300000 \
    -XX:+UseParallelOldGC \
    -XX:+PrintGC \
    -Dzeromq.config.server.port=$1 \
    -Dzeromq.config.instance.id=$2 \
    -Dzeromq.config.query.list=$3 \
    -Dzeromq.config.trt.list=$4 \
     ${JVM_OPTS} com.bist.zeromq.ClientProcess