#!/usr/bin/env bash

##Usage : ./serverProcess [peerCommandPort] [peerIp] [instanceId] [QueryList] [TrtList]
##Usage : ./serverProcess  20123 1 1|2 4|5

VERSION=$(cat ../version.txt)


     "${JAVA_HOME}"/bin/java \
    -cp ../target/zeromq-${VERSION}-jar-with-dependencies.jar \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+TrustFinalNonStaticFields \
    -XX:+UnlockDiagnosticVMOptions \
    -XX:GuaranteedSafepointInterval=300000 \
    -XX:+UseParallelOldGC \
    -Xmx2g -Xms2g \
    -XX:NewRatio=1 \
    -XX:+PrintGC \
    -Dzeromq.config.server.port=$1 \
    -Dzeromq.config.server.ip=$2 \
    -Dzeromq.config.instance.id=$3 \
    -Dzeromq.config.query.list=$4 \
    -Dzeromq.config.trt.list=$5 \
     ${JVM_OPTS} com.bist.zeromq.ServerProcess